spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mlab?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&useAffectedRows=true
    username: root
    password: 3103Diaozuida
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8
  application:
    name: community-service

server:
  port: 8085

pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

management:
  endpoints:
    enabled-by-default: false

swagger:
  base-package: org.sse.community

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8888/eureka

security:
  oauth2:
    client:
      client-id: community-service
      client-secret: secret
      access-token-uri: http://localhost:8081/oauth/token
      user-authorization-uri: http://localhost:8081/oauth/authorize
    resource:
      token-info-uri: http://localhost:8081/oauth/check_token
